### ISSUE TITLE
Unable to load the firmware on my micro:bit

### ISSUE THREAD

**Issue by srcr** [virtualabs/btlejack-firmware#11]
I'm trying to load the firmware from the dist directory to my micro:bit but this keeps failing.
Off course I'm in maintenance mode and i have switched back and forth between the original firmware versions 0250 en 0253.

This is the .hex file I'm loading:

```
Name: btlejack-firmware-microbit.hex
Size: 470092 bytes (459 KiB)
SHA256: FE61EEF08BC64E4898CC9ABE047465A3B17A536BCFD39233FA2398B1654AA989
```

after dropping it on the storage the micro:bit resets and restarts in maintenance mode.
At this point I see the FAIL.TXT on the storage with the following content:

`The hex file you dropped isn't compatible with this mode or device. Are you in MAINTENANCE mode? See HELP FAQ.HTM`

My micro:bit has version v1.3 B on the print.

Any advice would be appreciated.

**Comment by srcr** [comment]
-- link to this item from my blog

**Comment by virtualabs** [comment]
Btlejack firmware is designed to be uploaded the normal way, not in maintenance mode. Maintenance mode is used to upgrade the interface firmware that runs on a secondary chip in charge of the USB interface. Connect your micro:bit WITHOUT pressing the reset button, and drop btlejack firmware on the associated mass storage device that shows up (should be named MICROBIT).

**Comment by srcr** [comment]
Ok, I thought the code was firmware. let me try it and see if I can get it going.

**Comment by srcr** [comment]
Things work like a charm. I'm currently sniffing my phone <-> FitBit traffic.
Naming this project btlejack-firmware put me in the wrong mind set that I needed to write this as firmware.
